### ISSUE TITLE
Call verify method on the void method?

### ISSUE THREAD

**Issue by andreykirson** [Book-Microservices-v2/chapter07#1]
Does it need to call the verify method on a void method?
https://github.com/Book-Microservices-v2/chapter07/blob/9ef2931ab44469991326bd3f5b5292980c30fc50/multiplication/src/test/java/microservices/book/multiplication/challenge/ChallengeServiceTest.java#L57

**Comment by mechero** [comment]
This line is there to verify that the method is called and the argument matches the expected one. It's useful even when the method does not return anything, but you want to make sure it's called.

Does this answer your question?

**Comment by andreykirson** [comment]
thanks for such operative answer
